
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Ideal extends javax.swing.JFrame {
    String temp="";
    Double ti, bt, h1;
    public Ideal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();
        Saran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 90, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 80, 50, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 120, 50, 14);

        jLabel4.setText("Berat badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 160, 70, 14);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 200, 80, 14);
        getContentPane().add(Nama);
        Nama.setBounds(220, 70, 130, 30);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(220, 110, 60, 30);
        getContentPane().add(Berat);
        Berat.setBounds(220, 150, 60, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Perempuan");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(220, 200, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Laki - laki");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(330, 200, 80, 23);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(120, 250, 70, 23);

        jButton2.setText("Coba Lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(223, 250, 90, 23);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(343, 250, 70, 23);

        jLabel6.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 300, 180, 14);
        getContentPane().add(Ideal);
        Ideal.setBounds(280, 290, 40, 30);

        jLabel7.setText("Cm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 120, 30, 14);

        jLabel8.setText("Kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 160, 20, 14);

        jLabel9.setText("Kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 300, 20, 14);

        jLabel10.setText("Hasil diagnosa kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 340, 140, 14);
        getContentPane().add(Hasil);
        Hasil.setBounds(70, 370, 370, 30);
        getContentPane().add(Saran);
        Saran.setBounds(70, 410, 370, 30);

        setBounds(0, 0, 547, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        if(Nama.getText().equals("")||Tinggi.getText().equals("")
                |Berat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data harus diisikan semua");
        }else if(jRadioButton1.isSelected()||jRadioButton2.isSelected()){
            try{
                Proses();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Inputan ada yang belum diisi");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Radio Button hsrus dipilih");
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Nama.setText("");
        Tinggi.setText("");
        Berat.setText("");
        Ideal.setText("");
        Hasil.setText("");
        Saran.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ideal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField Ideal;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Saran;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(Tinggi.getText());
        bt = Double.parseDouble(Berat.getText());
        
        if(jRadioButton1.isSelected()){
            h1 = (ti - 100) * 1;
        } else if(jRadioButton2.isSelected()){
            h1 = (ti - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        
        if(h1 < bt){
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText() + ", sepertinya anda overweight");
            Saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        } else if (h1 > bt){
            Ideal.setText(temp);
            Hasil.setText("Maaf " + Nama.getText() + ", sepertinya anda underweight");
            Saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }else {
            Ideal.setText(temp);
            Hasil.setText("Hallo" + Nama.getText() + ", berat anda sudah ideal");
            Saran.setText("Lanjutkan pola makan teratur dan gaya hidup hesat :) ");
        }
    }
}
